[project]
name = "cardb"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bs4>=0.0.2",
    "notion-client>=2.3.0",
    "ollama>=0.4.5",
    "requests>=2.32.3",
    "tqdm>=4.67.1",
]
